### ISSUE TITLE
shh does not work if strace is not installed

### ISSUE THREAD

**Issue by token0** [synacktiv/shh#1]
Error message:

`Error: No such file or directory (os error 2)`

Installing strace fixed that. Should be some minimal message about strace dependency.

**Comment by desbma-s1n** [comment]
It's clearly stated [in the README](https://github.com/synacktiv/shh?tab=readme-ov-file#dependencies) that strace is required. If you install `shh` from the Debian or AUR package, strace is a required dependency and should already be installed. I have added a bit more context to the error anyway in eb0bca27f774a72a17e313a4b4f25e546ac363c2.
